name: Build myprogram

on:
  push:
    branches: [main]

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S myprogram -B myprogram/build

      - name: Build
        run: cmake --build myprogram/build

      - name: Install
        run: DESTDIR=myprogram/install cmake --install myprogram/build
