name: Build myprogram w/ reusable action

on:
  workflow_dispatch:

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: CMake Build & Install
        uses: ./.github/actions/cmake-build
        with:
          src_dir: myprogram
