name: Build myprogram (reusable)

on:
  workflow_call:
    inputs:
      options:
        type: string
        description: "Additional options to pass to CMake"
      suffix:
        type: string
        description: "A suffix to add to the uploaded artifact filename"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: CMake build & install
        uses: ./.github/actions/cmake-build
        with:
          src_dir: myprogram
          options: ${{ inputs.options }}

      - name: Package
        run: tar Jcf myprogram-${{ github.ref_name }}${{ inputs.suffix }}.tar.xz --transform 's,^\.,myprogram-${{ github.ref_name }},' -C install .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: myprogram-${{ github.ref_name }}${{ inputs.suffix }}.tar.xz
          path: myprogram-${{ github.ref_name }}${{ inputs.suffix }}.tar.xz
