name: Release myprogram

on:
  push:
    tags:
      - v*

jobs:

  build:
    uses: ./.github/workflows/3-reusable-build.yml

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifacts
        run: |
          for d in artifacts/*; do mv $d/* .; done
          rm -rf artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: '*'
