name: Build myprogram w/ matrix

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        variant: [Debug, Release]
    uses: ./.github/workflows/3-reusable-build.yml
    with:
      options: -DCMAKE_BUILD_TYPE=${{ matrix.variant}}
      suffix: -${{ matrix.variant }}
